apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: csi-snapshot-webhook-vpa
  namespace: {{ .Release.Namespace }}
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: csi-snapshot-validation
      minAllowed:
        memory: {{ .Values.csiSnapshotValidationWebhook.resources.memory }}
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: csi-snapshot-validation
  updatePolicy:
    updateMode: Auto
