apiVersion: v1
kind: Service
metadata:
  name: csi-snapshot-validation
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: snapshot-validation
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
